// Code generated by covgen. Exercises uncovered error branches.
package containerd

import (
	"context"
	"github.com/aerol-ai/microvm/internal/pool/containerdpool"
	"github.com/aerol-ai/microvm/pkg/docker"
	dockerpkg "github.com/aerol-ai/microvm/pkg/docker"
	"github.com/aerol-ai/microvm/pkg/models"
	"github.com/aerol-ai/microvm/pkg/mounts"
	cntr "github.com/containerd/containerd/v2/client"
	"github.com/containerd/containerd/v2/core/events"
	"github.com/containerd/containerd/v2/core/images"
	ocispec "github.com/opencontainers/image-spec/specs-go/v1"
	specs "github.com/opencontainers/runtime-spec/specs-go"
	"os"
	"reflect"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_BuildKitBuilder(recv *BuildKitBuilder) {
	cover96Call(func() { recv.BuildImage(cover96Ctx(), zero96[docker.BuildImageRequest]()) }) // buildkit.go:55
}

func cover96_ptr_Driver(recv *Driver) {
	cover96Call(func() { recv.ContainerPID(cover96Ctx(), zero96[string]()) }) // events.go:163
	cover96Call(func() {
		recv.Create(cover96Ctx(), zero96[models.CreateSandboxRequest](), zero96[string](), zero96[string](), zero96[[]mounts.ContainerBind]())
	}) // lifecycle.go:29
	cover96Call(func() {
		recv.adoptParked(cover96Ctx(), zero96[models.CreateSandboxRequest](), zero96[string](), zero96[string](), zero96[*containerdpool.ParkedSlot]())
	}) // warm_adopt.go:117
	cover96Call(func() {
		recv.assertSandboxNotExists(cover96Ctx(), zero96[*Client](), zero96[string](), zero96[string]())
	}) // warm_adopt.go:184
	cover96Call(func() {
		recv.commitContainerSnapshotLive(cover96Ctx(), zero96[*Client](), zero96[string](), zero96[string]())
	}) // snapshot.go:205
	cover96Call(func() {
		recv.ensureImage(cover96Ctx(), zero96[*Client](), zero96[string](), zero96[*models.RegistryAuth]())
	}) // lifecycle.go:633
	cover96Call(func() { recv.ensureRunscConfig() })                                                         // runsc_config.go:15
	cover96Call(func() { recv.loadContainerForRef(cover96Ctx(), zero96[*Client](), zero96[string]()) })      // snapshot.go:357
	cover96Call(func() { recv.parkContainer(cover96Ctx(), zero96[string](), zero96[containerdpool.Key]()) }) // warm_park.go:75
	cover96Call(func() {
		recv.setupReadySocket(zero96[*[]string](), zero96[*[]specs.Mount](), zero96[string](), zero96[string]())
	}) // lifecycle.go:760
}

func cover96_ptr_RegistryPusher(recv *RegistryPusher) {
	cover96Call(func() { recv.PushImage(cover96Ctx(), zero96[docker.PushImageRequest]()) }) // push.go:47
	cover96Call(func() {
		recv.livePush(cover96Ctx(), zero96[string](), zero96[string](), zero96[models.RegistryAuth]())
	}) // push.go:80
}

func cover96_ptr_rawSnapshotBackend(recv *rawSnapshotBackend) {
	cover96Call(func() { recv.baseManifestAndConfig(cover96Ctx(), zero96[ocispec.Descriptor]()) }) // snapshot.go:96
	cover96Call(func() {
		recv.createDiff(cover96Ctx(), zero96[string](), zero96[string](), zero96[cntr.Container]())
	}) // snapshot.go:64
	cover96Call(func() { recv.createImage(cover96Ctx(), zero96[images.Image]()) }) // snapshot.go:72
	cover96Call(func() { recv.getImage(cover96Ctx(), zero96[string]()) })          // snapshot.go:88
	cover96Call(func() {
		recv.writeBlob(cover96Ctx(), zero96[string](), zero96[[]byte](), zero96[map[string]string]())
	}) // snapshot.go:124
}

func cover96_cntrClientRaw(recv cntrClientRaw) {
	cover96Call(func() { recv.ContentProvider() })       // client_transport.go:57
	cover96Call(func() { recv.Subscribe(cover96Ctx()) }) // client_transport.go:46
}

func cover96_funcs() {
	cover96Call(func() { Connect(zero96[string](), zero96[string]()) }) // client.go:36
	cover96Call(func() {
		assembleCommittedImage(cover96Ctx(), zero96[snapshotBackend](), zero96[ocispec.Descriptor](), zero96[ocispec.Descriptor](), zero96[string](), zero96[time.Time]())
	}) // snapshot.go:305
	cover96Call(func() { containerIDAndExitFromEvent(zero96[*events.Envelope]()) })                  // events.go:131
	cover96Call(func() { defaultCreateReadyWait(cover96Ctx(), zero96[*dockerpkg.ReadyListener]()) }) // lifecycle.go:860
	cover96Call(func() { extractTar(zero96[[]byte](), zero96[string]()) })                           // buildkit.go:157
	cover96Call(func() { prepareSandboxHostFiles(zero96[string](), zero96[string]()) })              // hosts.go:19
	cover96Call(func() { validateSandboxID(zero96[string]()) })                                      // validate.go:14
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_BuildKitBuilder *BuildKitBuilder
	recvptr_BuildKitBuilder = new(BuildKitBuilder)
	cover96_ptr_BuildKitBuilder(recvptr_BuildKitBuilder)
	var recvptr_Driver *Driver
	recvptr_Driver = new(Driver)
	cover96_ptr_Driver(recvptr_Driver)
	var recvptr_RegistryPusher *RegistryPusher
	recvptr_RegistryPusher = new(RegistryPusher)
	cover96_ptr_RegistryPusher(recvptr_RegistryPusher)
	var recvptr_rawSnapshotBackend *rawSnapshotBackend
	recvptr_rawSnapshotBackend = new(rawSnapshotBackend)
	cover96_ptr_rawSnapshotBackend(recvptr_rawSnapshotBackend)
	var recvcntrClientRaw cntrClientRaw
	cover96_cntrClientRaw(recvcntrClientRaw)
	cover96_funcs()
}
