// Code generated by covgen. Exercises uncovered error branches.
package isolate

import (
	"context"
	"net/http"
	"os"
	"os/exec"
	"reflect"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_Host(recv *Host) {
	cover96Call(func() { recv.SetEgressObserver(zero96[EgressObserver]()) })                          // host.go:93
	cover96Call(func() { recv.SetEgressPolicy(zero96[string](), zero96[EgressPolicy]()) })            // egress.go:34
	cover96Call(func() { recv.Start(cover96Ctx()) })                                                  // host.go:208
	cover96Call(func() { recv.Stop() })                                                               // host.go:422
	cover96Call(func() { recv.grantJailAccess() })                                                    // host.go:473
	cover96Call(func() { recv.observeEgress(zero96[string](), zero96[string](), zero96[string]()) })  // host.go:102
	cover96Call(func() { recv.startSlotServerLocked(zero96[int]()) })                                 // egress.go:83
	cover96Call(func() { recv.waitReady(cover96Ctx(), zero96[*exec.Cmd](), zero96[*http.Client]()) }) // host.go:351
}

func cover96_ptr_jailRealized(recv *jailRealized) {
	cover96Call(func() { recv.closeFD() })  // jail_realized.go:26
	cover96Call(func() { recv.teardown() }) // jail_realized.go:36
}

func cover96_cgroupFS(recv cgroupFS) {
	cover96Call(func() { recv.applyCaps(zero96[string](), zero96[float64](), zero96[int](), zero96[int]()) }) // cgroup.go:92
	cover96Call(func() { recv.enableControllers() })                                                          // cgroup.go:63
	cover96Call(func() { recv.ensure(zero96[string](), zero96[float64](), zero96[int](), zero96[int]()) })    // cgroup.go:36
	cover96Call(func() { recv.remove(zero96[string]()) })                                                     // cgroup.go:122
}

func cover96_funcs() {
	cover96Call(func() { PrepareJailBase(zero96[string](), zero96[string]()) })                             // chroot.go:42
	cover96Call(func() { cloneDevNode(zero96[string](), zero96[string]()) })                                // chroot_other.go:12
	cover96Call(func() { copyFileMode(zero96[string](), zero96[string](), zero96[os.FileMode]()) })         // chroot.go:281
	cover96Call(func() { encodeJailShimSpec(zero96[jailShimSpec]()) })                                      // seccomp.go:230
	cover96Call(func() { linkGroupJail(zero96[string](), zero96[string](), zero96[int](), zero96[int]()) }) // chroot.go:121
	cover96Call(func() { parseLDD(zero96[[]byte]()) })                                                      // chroot.go:238
	cover96Call(func() { resolveSharedLibs(zero96[string]()) })                                             // chroot.go:191
	cover96Call(func() { runningAsRoot() })                                                                 // chroot_other.go:14
	cover96Call(func() { writeControl(zero96[string](), zero96[string]()) })                                // cgroup.go:142
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_Host *Host
	recvptr_Host = new(Host)
	cover96_ptr_Host(recvptr_Host)
	var recvptr_jailRealized *jailRealized
	recvptr_jailRealized = new(jailRealized)
	cover96_ptr_jailRealized(recvptr_jailRealized)
	var recvcgroupFS cgroupFS
	cover96_cgroupFS(recvcgroupFS)
	cover96_funcs()
}
