// Code generated by covgen. Exercises uncovered error branches.
package daemon

import (
	"context"
	"github.com/aerol-ai/microvm/internal/config"
	cntr "github.com/aerol-ai/microvm/internal/runtime/containerd"
	"github.com/aerol-ai/microvm/internal/service"
	"github.com/aerol-ai/microvm/internal/store"
	"github.com/aerol-ai/microvm/pkg/capacity"
	"github.com/aerol-ai/microvm/pkg/docker"
	"github.com/aerol-ai/microvm/pkg/docker/netrules"
	"log/slog"
	"os"
	"reflect"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_firecrackerTemplateSnapshotterAdapter(recv *firecrackerTemplateSnapshotterAdapter) {
	cover96Call(func() { recv.SnapshotTemplate(cover96Ctx(), zero96[service.TemplateSnapshotRequest]()) }) // daemon.go:2021
}

func cover96_ptr_multiEventsSource(recv *multiEventsSource) {
	cover96Call(func() { recv.StreamEvents(cover96Ctx(), zero96[chan docker.DockerEvent]()) }) // container_engine_wiring.go:122
}

func cover96_funcs() {
	cover96Call(func() { Run(cover96Ctx(), zero96[*slog.Logger](), zero96[ProviderFactory]()) }) // daemon.go:80
	cover96Call(func() { newHostPortForwarder(zero96[*slog.Logger]()) })                         // ingress_routing_wiring.go:150
	cover96Call(func() {
		startAutoImportReconciler(cover96Ctx(), zero96[*slog.Logger](), zero96[config.Config](), zero96[*store.Store](), zero96[*service.Service]())
	}) // daemon.go:1306
	cover96Call(func() {
		startClusterSecretRefanoutRetry(cover96Ctx(), zero96[*service.Service](), zero96[*slog.Logger]())
	}) // daemon.go:1160
	cover96Call(func() {
		startSnapshotPushReconciler(cover96Ctx(), zero96[*slog.Logger](), zero96[config.Config](), zero96[*store.Store](), zero96[*service.Service](), zero96[*docker.Client](), zero96[*containerdEngineWiring]())
	}) // daemon.go:1383
	cover96Call(func() {
		startTemplateArtifactPushReconciler(cover96Ctx(), zero96[*slog.Logger](), zero96[config.Config](), zero96[*store.Store](), zero96[*service.Service](), zero96[*docker.Client]())
	}) // daemon.go:1576
	cover96Call(func() {
		startTemplateRotationReconciler(cover96Ctx(), zero96[*slog.Logger](), zero96[config.Config](), zero96[*store.Store](), zero96[*service.Service]())
	}) // daemon.go:1472
	cover96Call(func() {
		wireContainerEngine(cover96Ctx(), zero96[config.Config](), zero96[*slog.Logger](), zero96[*service.Service](), zero96[*store.Store](), zero96[*docker.Client](), zero96[*netrules.Manager](), zero96[*capacity.Admitter]())
	}) // container_engine_wiring.go:30
	cover96Call(func() {
		wireContainerdNativeNetnsPool(cover96Ctx(), zero96[config.Config](), zero96[*slog.Logger](), zero96[*store.Store](), zero96[*cntr.Driver]())
	}) // containerd_netns_wiring.go:37
	cover96Call(func() {
		wireContainerdWarmPool(cover96Ctx(), zero96[config.Config](), zero96[*slog.Logger](), zero96[*cntr.Driver](), zero96[*capacity.Admitter]())
	}) // containerd_warm_wiring.go:39
	cover96Call(func() {
		wireDockerWarmPool(cover96Ctx(), zero96[config.Config](), zero96[*slog.Logger](), zero96[*docker.Client](), zero96[*capacity.Admitter]())
	}) // docker_warm_wiring.go:15
	cover96Call(func() {
		wireIsolateRuntime(cover96Ctx(), zero96[config.Config](), zero96[*slog.Logger](), zero96[*service.Service]())
	}) // isolate_wiring.go:23
	cover96Call(func() {
		wireWasmRuntime(cover96Ctx(), zero96[config.Config](), zero96[*slog.Logger](), zero96[*service.Service](), zero96[*store.Store]())
	}) // wasm_wiring.go:31
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_firecrackerTemplateSnapshotterAdapter *firecrackerTemplateSnapshotterAdapter
	recvptr_firecrackerTemplateSnapshotterAdapter = new(firecrackerTemplateSnapshotterAdapter)
	cover96_ptr_firecrackerTemplateSnapshotterAdapter(recvptr_firecrackerTemplateSnapshotterAdapter)
	var recvptr_multiEventsSource *multiEventsSource
	recvptr_multiEventsSource = new(multiEventsSource)
	cover96_ptr_multiEventsSource(recvptr_multiEventsSource)
	cover96_funcs()
}
