// Code generated by covgen. Exercises uncovered error branches.
package wasm

import (
	"bytes"
	"context"
	"github.com/tetratelabs/wazero/api"
	"os"
	"reflect"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_MultiInstanceEngine(recv *MultiInstanceEngine) {
	cover96Call(func() { recv.Instantiate(cover96Ctx(), zero96[string](), zero96[Capabilities]()) })           // engine_multi.go:142
	cover96Call(func() { recv.Run(cover96Ctx(), zero96[string](), zero96[Capabilities](), zero96[string]()) }) // engine_multi.go:180
	cover96Call(func() { recv.ensureNetworkHostLocked(cover96Ctx()) })                                         // engine_multi_network.go:237
}

func cover96_ptr_wazeroEngine(recv *wazeroEngine) {
	cover96Call(func() { recv.Close(cover96Ctx()) })                                               // engine_wazero.go:571
	cover96Call(func() { recv.Instantiate(cover96Ctx(), zero96[Capabilities]()) })                 // engine_wazero.go:202
	cover96Call(func() { recv.LoadModule(cover96Ctx(), zero96[string](), zero96[LoadOptions]()) }) // engine_wazero.go:153
	cover96Call(func() {
		recv.RestoreSnapshot(cover96Ctx(), zero96[SnapshotRestoreInput](), zero96[Capabilities]())
	}) // engine_wazero.go:538
	cover96Call(func() { recv.Run(cover96Ctx(), zero96[Capabilities](), zero96[string]()) }) // engine_wazero.go:382
	cover96Call(func() { recv.beginCall(cover96Ctx()) })                                     // engine_wazero.go:271
	cover96Call(func() { recv.ensureNetworkHost(cover96Ctx()) })                             // wazero_network.go:60
	cover96Call(func() { recv.ensureOpenLocked() })                                          // engine_wazero.go:246
	cover96Call(func() { recv.ensureWasiCompatHosts(cover96Ctx()) })                         // engine_wazero.go:128
	cover96Call(func() { recv.ensureWasiHTTPHost(cover96Ctx()) })                            // wazero_wasi_compat.go:78
	cover96Call(func() { recv.ensureWasiSocketsHost(cover96Ctx()) })                         // wazero_wasi_compat.go:20
	cover96Call(func() { recv.initRuntime(cover96Ctx(), zero96[int]()) })                    // engine_wazero.go:60
	cover96Call(func() { recv.instantiateLocked(cover96Ctx(), zero96[Capabilities]()) })     // engine_wazero.go:211
	cover96Call(func() {
		recv.instantiateWithIOLocked(cover96Ctx(), zero96[Capabilities](), zero96[*bytes.Buffer](), zero96[*bytes.Buffer]())
	}) // engine_wazero.go:419
	cover96Call(func() { recv.stopActiveLocked(cover96Ctx()) }) // engine_wazero.go:295
}

func cover96_funcs() {
	cover96Call(func() { MemoryLimitPages(zero96[int]()) })                               // fuel.go:25
	cover96Call(func() { WriteSnapshotDir(zero96[string](), zero96[SnapshotCapture]()) }) // snapshot_codec.go:78
	cover96Call(func() { moduleLookupFile(zero96[api.Module](), zero96[int32]()) })       // wazero_listen.go:34
	cover96Call(func() { newBaseRuntime(cover96Ctx(), zero96[uint32]()) })                // engine_wazero.go:99
	cover96Call(func() { withWasip1Meter(cover96Ctx(), zero96[*NetworkHook]()) })         // wazero_wasip1_meter.go:126
	cover96Call(func() { zstdCompress(zero96[[]byte]()) })                                // snapshot_codec.go:213
	cover96Call(func() { zstdDecompressMax(zero96[[]byte](), zero96[uint64]()) })         // snapshot_codec.go:231
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_MultiInstanceEngine *MultiInstanceEngine
	recvptr_MultiInstanceEngine = new(MultiInstanceEngine)
	cover96_ptr_MultiInstanceEngine(recvptr_MultiInstanceEngine)
	var recvptr_wazeroEngine *wazeroEngine
	recvptr_wazeroEngine = new(wazeroEngine)
	cover96_ptr_wazeroEngine(recvptr_wazeroEngine)
	cover96_funcs()
}
