// Code generated by covgen. Exercises uncovered error branches.
package hostport

import (
	"context"
	"os"
	"reflect"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_Forwarder(recv *Forwarder) {
	cover96Call(func() { recv.Reconcile(zero96[map[int]Target]()) })                // forwarder.go:334
	cover96Call(func() { recv.deleteRulesLocked(zero96[int](), zero96[Target]()) }) // forwarder.go:271
	cover96Call(func() { recv.ensureChains() })                                     // forwarder.go:134
	cover96Call(func() { recv.ensureRulesLocked(zero96[int](), zero96[Target]()) }) // forwarder.go:242
	cover96Call(func() { recv.reconcileLocked(zero96[map[int]Target]()) })          // forwarder.go:371
}

func cover96_ptr_iptablesBackend(recv *iptablesBackend) {
	cover96Call(func() { recv.Append(zero96[string](), zero96[string]()) })                // iptables_backend.go:28
	cover96Call(func() { recv.ChainExists(zero96[string](), zero96[string]()) })           // iptables_backend.go:18
	cover96Call(func() { recv.Delete(zero96[string](), zero96[string]()) })                // iptables_backend.go:31
	cover96Call(func() { recv.Exists(zero96[string](), zero96[string]()) })                // iptables_backend.go:22
	cover96Call(func() { recv.Insert(zero96[string](), zero96[string](), zero96[int]()) }) // iptables_backend.go:25
	cover96Call(func() { recv.List(zero96[string](), zero96[string]()) })                  // iptables_backend.go:34
	cover96Call(func() { recv.NewChain(zero96[string](), zero96[string]()) })              // iptables_backend.go:21
}

func cover96_funcs() {
	cover96Call(func() { FlushConntrack(zero96[int]()) })                                                      // conntrack_other.go:6
	cover96Call(func() { NewIPTablesBackend() })                                                               // iptables_backend.go:10
	cover96Call(func() { platformEnableIPForward() })                                                          // sysctl_other.go:5
	cover96Call(func() { ruleMatches(zero96[string](), zero96[[]string](), zero96[int](), zero96[Target]()) }) // forwarder.go:423
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_Forwarder *Forwarder
	recvptr_Forwarder = new(Forwarder)
	cover96_ptr_Forwarder(recvptr_Forwarder)
	var recvptr_iptablesBackend *iptablesBackend
	recvptr_iptablesBackend = new(iptablesBackend)
	cover96_ptr_iptablesBackend(recvptr_iptablesBackend)
	cover96_funcs()
}
