// Code generated by covgen. Exercises uncovered error branches.
package e2b

import (
	"context"
	svcmetrics "github.com/aerol-ai/microvm/internal/service"
	"github.com/aerol-ai/microvm/pkg/models"
	"log/slog"
	"net/http"
	"os"
	"reflect"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_handlers(recv *handlers) {
	cover96Call(func() { recv.connectSandbox(zero96[http.ResponseWriter](), zero96[*http.Request]()) }) // handlers.go:380
	cover96Call(func() { recv.createSandbox(zero96[http.ResponseWriter](), zero96[*http.Request]()) })  // handlers.go:48
	cover96Call(func() { recv.createSnapshot(zero96[http.ResponseWriter](), zero96[*http.Request]()) }) // handlers.go:500
	cover96Call(func() { recv.deleteSnapshot(zero96[http.ResponseWriter](), zero96[*http.Request]()) }) // handlers.go:629
	cover96Call(func() { recv.listSandboxes(zero96[http.ResponseWriter](), zero96[*http.Request]()) })  // handlers.go:229
	cover96Call(func() { recv.listSnapshots(zero96[http.ResponseWriter](), zero96[*http.Request]()) })  // handlers.go:555
	cover96Call(func() {
		recv.loadReplayableCreateResult(cover96Ctx(), zero96[*models.IdempotentRequestRecord]())
	}) // handlers.go:905
	cover96Call(func() { recv.persistSandboxMeta(cover96Ctx(), zero96[string](), zero96[sandboxMeta]()) }) // handlers.go:894
	cover96Call(func() { recv.resolveSnapshotDeleteTarget(cover96Ctx(), zero96[string]()) })               // handlers.go:975
	cover96Call(func() { recv.resolveTemplate(cover96Ctx(), zero96[string]()) })                           // handlers.go:849
	cover96Call(func() { recv.runtimeProxy(zero96[http.ResponseWriter](), zero96[*http.Request]()) })      // runtime_proxy.go:16
	cover96Call(func() { recv.updateTimeout(zero96[http.ResponseWriter](), zero96[*http.Request]()) })     // handlers.go:461
	cover96Call(func() { recv.waitForCreateReplay(cover96Ctx(), zero96[string]()) })                       // handlers.go:926
}

func cover96_funcs() {
	cover96Call(func() { clusterListMode(zero96[*svcmetrics.Service](), zero96[*http.Request]()) }) // handlers.go:215
	cover96Call(func() {
		createRequestFingerprint(zero96[string](), zero96[string](), zero96[models.CreateSandboxRequest](), zero96[sandboxMeta]())
	}) // meta.go:317
	cover96Call(func() { loadTemplateMap(zero96[*slog.Logger]()) })                                                      // handlers.go:1280
	cover96Call(func() { parseMetadataFilter(zero96[string]()) })                                                        // handlers.go:1179
	cover96Call(func() { sandboxMetaFromNative(zero96[*models.Sandbox](), zero96[compatBlob]()) })                       // meta.go:108
	cover96Call(func() { sandboxMetaToState(zero96[sandboxMeta]()) })                                                    // meta.go:165
	cover96Call(func() { writeStoreAwareError(zero96[*slog.Logger](), zero96[http.ResponseWriter](), zero96[error]()) }) // errors.go:60
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_handlers *handlers
	recvptr_handlers = new(handlers)
	cover96_ptr_handlers(recvptr_handlers)
	cover96_funcs()
}
