// Code generated by covgen. Exercises uncovered error branches.
package api

import (
	"context"
	"expvar"
	"io"
	"net/http"
	"os"
	"reflect"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_Server(recv *Server) {
	cover96Call(func() { recv.clusterControlHeaderGuard(zero96[http.Handler]()) })                    // middleware.go:30
	cover96Call(func() { recv.handleHealth(zero96[http.ResponseWriter](), zero96[*http.Request]()) }) // server.go:122
}

func cover96_funcs() {
	cover96Call(func() {
		collectPrometheusSamples(zero96[string](), zero96[expvar.Var](), zero96[[]prometheusLabel](), zero96[*[]prometheusSample]())
	}) // prometheus.go:69
	cover96Call(func() { hasClusterControlHeader(zero96[http.Header]()) }) // middleware.go:50
	cover96Call(func() { prometheusMetricName(zero96[string]()) })         // prometheus.go:133
	cover96Call(func() { prometheusValue(zero96[expvar.Var]()) })          // prometheus.go:94
	cover96Call(func() { writePrometheusExpvars(zero96[io.Writer]()) })    // prometheus.go:37
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_Server *Server
	recvptr_Server = new(Server)
	cover96_ptr_Server(recvptr_Server)
	cover96_funcs()
}
