// Code generated by covgen. Exercises uncovered error branches.
package main

import (
	"context"
	"github.com/aerol-ai/microvm/cmd/toolboxd/sessions"
	"github.com/gorilla/websocket"
	"io"
	"log/slog"
	"net/http"
	"os"
	"os/exec"
	"reflect"
	"sync"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_daytonaCommandStream(recv *daytonaCommandStream) {
	cover96Call(func() { recv.broadcast(zero96[sessions.Stream](), zero96[[]byte]()) }) // daytona_process.go:85
}

func cover96_ptr_server(recv *server) {
	cover96Call(func() {
		recv.drainEnvdProcessFrames(zero96[*connectJSONStream](), zero96[chan sessions.Frame](), zero96[bool]())
	}) // envd.go:805
	cover96Call(func() { recv.handleDaytonaCodeRun(zero96[http.ResponseWriter](), zero96[*http.Request]()) })    // daytona_code_run.go:66
	cover96Call(func() { recv.handleDaytonaGitCommit(zero96[http.ResponseWriter](), zero96[*http.Request]()) })  // daytona_files_git.go:366
	cover96Call(func() { recv.handleDaytonaGitHistory(zero96[http.ResponseWriter](), zero96[*http.Request]()) }) // daytona_files_git.go:462
	cover96Call(func() { recv.handleDaytonaListFiles(zero96[http.ResponseWriter](), zero96[*http.Request]()) })  // daytona_files_git.go:137
	cover96Call(func() {
		recv.handleDaytonaSessionDelete(zero96[http.ResponseWriter](), zero96[*http.Request](), zero96[string]())
	}) // daytona_process.go:505
	cover96Call(func() { recv.handleEnvdFilesystemMakeDir(zero96[http.ResponseWriter](), zero96[*http.Request]()) }) // envd.go:888
	cover96Call(func() { recv.handleEnvdFilesystemMove(zero96[http.ResponseWriter](), zero96[*http.Request]()) })    // envd.go:922
	cover96Call(func() { recv.handleEnvdMultipartWrite(zero96[http.ResponseWriter](), zero96[*http.Request]()) })    // envd.go:523
	cover96Call(func() { recv.handleEnvdOctetStreamWrite(zero96[http.ResponseWriter](), zero96[*http.Request]()) })  // envd.go:490
	cover96Call(func() { recv.handleEnvdProcessCloseStdin(zero96[http.ResponseWriter](), zero96[*http.Request]()) }) // envd.go:739
	cover96Call(func() { recv.handleEnvdProcessConnect(zero96[http.ResponseWriter](), zero96[*http.Request]()) })    // envd.go:652
	cover96Call(func() { recv.handleEnvdProcessSendInput(zero96[http.ResponseWriter](), zero96[*http.Request]()) })  // envd.go:683
	cover96Call(func() { recv.handleEnvdProcessSendSignal(zero96[http.ResponseWriter](), zero96[*http.Request]()) }) // envd.go:717
	cover96Call(func() { recv.handleEnvdProcessStart(zero96[http.ResponseWriter](), zero96[*http.Request]()) })      // envd.go:601
	cover96Call(func() { recv.handleEnvdProcessUpdate(zero96[http.ResponseWriter](), zero96[*http.Request]()) })     // envd.go:662
	cover96Call(func() { recv.handleExec(zero96[http.ResponseWriter](), zero96[*http.Request]()) })                  // main.go:572
	cover96Call(func() { recv.handleExecStream(zero96[http.ResponseWriter](), zero96[*http.Request]()) })            // exec_stream.go:65
	cover96Call(func() { recv.handleProxy(zero96[http.ResponseWriter](), zero96[*http.Request]()) })                 // main.go:729
	cover96Call(func() { recv.lookupDaytonaSession(zero96[string]()) })                                              // daytona_process.go:654
	cover96Call(func() { recv.routes() })                                                                            // main.go:336
	cover96Call(func() {
		recv.runDaytonaSessionCommand(zero96[*sessions.Session](), zero96[*daytonaSessionState](), zero96[*daytonaCommandState]())
	}) // daytona_process.go:679
	cover96Call(func() { recv.runWithPTY(zero96[*websocket.Conn](), zero96[*exec.Cmd](), zero96[*execStreamStartMsg]()) }) // exec_stream.go:107
	cover96Call(func() { recv.runWithPipes(zero96[*websocket.Conn](), zero96[*exec.Cmd]()) })                              // exec_stream.go:163
	cover96Call(func() {
		recv.streamDaytonaSessionCommandLogs(zero96[http.ResponseWriter](), zero96[*http.Request](), zero96[*daytonaCommandState]())
	}) // daytona_process.go:610
	cover96Call(func() {
		recv.streamEnvdProcessSession(zero96[http.ResponseWriter](), zero96[*http.Request](), zero96[*sessions.Session](), zero96[*envdProcessState]())
	}) // envd.go:760
}

func cover96_funcs() {
	cover96Call(func() { envdPermissionString(zero96[os.FileMode]()) })                                // envd.go:1034
	cover96Call(func() { forwardShutdownSignals(zero96[*slog.Logger](), zero96[*http.Server]()) })     // main.go:285
	cover96Call(func() { interpretWaitResult(zero96[error]()) })                                       // exec_stream.go:312
	cover96Call(func() { listEnvdEntries(zero96[string](), zero96[int]()) })                           // envd.go:1042
	cover96Call(func() { normalizeSandboxPath(zero96[string](), zero96[string]()) })                   // main.go:483
	cover96Call(func() { pumpReader(zero96[*websocket.Conn](), zero96[io.Reader](), zero96[byte]()) }) // exec_stream.go:269
	cover96Call(func() {
		pumpReaderLocked(zero96[*websocket.Conn](), zero96[io.Reader](), zero96[byte](), zero96[*sync.Mutex]())
	}) // exec_stream.go:287
	cover96Call(func() { pumpSession(zero96[*server](), zero96[*websocket.Conn](), zero96[*sessions.Session]()) }) // sessions_handler.go:246
	// skip readConnectJSONRequest (envd.go:1122)
	cover96Call(func() { resolveDaytonaPath(zero96[string](), zero96[bool]()) })         // daytona_files_git.go:515
	cover96Call(func() { startUserCommand(zero96[*slog.Logger](), zero96[[]string]()) }) // main.go:264
	cover96Call(func() { writeCodeRunScript(zero96[string](), zero96[string]()) })       // daytona_code_run.go:165
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_daytonaCommandStream *daytonaCommandStream
	recvptr_daytonaCommandStream = new(daytonaCommandStream)
	cover96_ptr_daytonaCommandStream(recvptr_daytonaCommandStream)
	var recvptr_server *server
	recvptr_server = new(server)
	cover96_ptr_server(recvptr_server)
	cover96_funcs()
}
