// Code generated by covgen. Exercises uncovered error branches.
package v1

import (
	"context"
	"github.com/aerol-ai/microvm/internal/cluster"
	"github.com/aerol-ai/microvm/pkg/models"
	"net/http"
	"os"
	"reflect"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_AuditRateLimiter(recv *AuditRateLimiter) {
	cover96Call(func() { recv.PeerMiddleware(zero96[http.Handler]()) }) // audit_limit.go:104
	cover96Call(func() { recv.allow(zero96[string]()) })                // audit_limit.go:143
}

func cover96_ptr_handlers(recv *handlers) {
	cover96Call(func() { recv.addCustomDomain(zero96[http.ResponseWriter](), zero96[*http.Request]()) })                // handlers.go:328
	cover96Call(func() { recv.buildImage(zero96[http.ResponseWriter](), zero96[*http.Request]()) })                     // build.go:176
	cover96Call(func() { recv.clusterBuildImageWrap(zero96[http.ResponseWriter](), zero96[*http.Request]()) })          // build.go:57
	cover96Call(func() { recv.clusterCreateTemplateWrap(zero96[http.ResponseWriter](), zero96[*http.Request]()) })      // template.go:33
	cover96Call(func() { recv.clusterCreateWrap(zero96[http.ResponseWriter](), zero96[*http.Request]()) })              // cluster_handler.go:129
	cover96Call(func() { recv.clusterDeleteOrphan(zero96[http.ResponseWriter](), zero96[*http.Request]()) })            // cluster_handler.go:702
	cover96Call(func() { recv.clusterDestroyWrap(zero96[http.ResponseWriter](), zero96[*http.Request]()) })             // cluster_handler.go:536
	cover96Call(func() { recv.clusterInternalApply(zero96[http.ResponseWriter](), zero96[*http.Request]()) })           // cluster_handler.go:1056
	cover96Call(func() { recv.clusterInternalArtifactCatalog(zero96[http.ResponseWriter](), zero96[*http.Request]()) }) // cluster_handler.go:834
	cover96Call(func() {
		recv.clusterInternalArtifactCatalogEpoch(zero96[http.ResponseWriter](), zero96[*http.Request]())
	}) // cluster_handler.go:870
	cover96Call(func() { recv.clusterInternalDrainedNodes(zero96[http.ResponseWriter](), zero96[*http.Request]()) }) // cluster_handler.go:1670
	cover96Call(func() {
		recv.clusterInternalNodeStorageRetirements(zero96[http.ResponseWriter](), zero96[*http.Request]())
	}) // cluster_handler.go:788
	cover96Call(func() { recv.clusterInternalOwnedRecovery(zero96[http.ResponseWriter](), zero96[*http.Request]()) })      // cluster_handler.go:1321
	cover96Call(func() { recv.clusterInternalReassignStuck(zero96[http.ResponseWriter](), zero96[*http.Request]()) })      // cluster_handler.go:1352
	cover96Call(func() { recv.clusterInternalSandboxAudit(zero96[http.ResponseWriter](), zero96[*http.Request]()) })       // audit_handler.go:45
	cover96Call(func() { recv.clusterInternalSecretDelete(zero96[http.ResponseWriter](), zero96[*http.Request]()) })       // cluster_handler.go:1590
	cover96Call(func() { recv.clusterInternalSecretPut(zero96[http.ResponseWriter](), zero96[*http.Request]()) })          // cluster_handler.go:1551
	cover96Call(func() { recv.clusterInternalSelectPlacement(zero96[http.ResponseWriter](), zero96[*http.Request]()) })    // cluster_handler.go:1496
	cover96Call(func() { recv.clusterInternalStorageObligations(zero96[http.ResponseWriter](), zero96[*http.Request]()) }) // cluster_handler.go:971
	cover96Call(func() { recv.clusterListJSBundlesWrap(zero96[http.ResponseWriter](), zero96[*http.Request]()) })          // js_bundle_cluster.go:29
	cover96Call(func() { recv.clusterListNodeStorageRetirements(zero96[http.ResponseWriter](), zero96[*http.Request]()) }) // cluster_handler.go:930
	cover96Call(func() { recv.clusterListTemplatesWrap(zero96[http.ResponseWriter](), zero96[*http.Request]()) })          // template.go:78
	cover96Call(func() { recv.clusterListWrap(zero96[http.ResponseWriter](), zero96[*http.Request]()) })                   // cluster_handler.go:327
	cover96Call(func() { recv.clusterReclaimOrphanLocal(zero96[http.ResponseWriter](), zero96[*http.Request]()) })         // cluster_handler.go:642
	cover96Call(func() { recv.clusterRetireNodeStorage(zero96[http.ResponseWriter](), zero96[*http.Request]()) })          // cluster_handler.go:749
	cover96Call(func() {
		recv.clusterRevokeNodeStorageRetirement(zero96[http.ResponseWriter](), zero96[*http.Request]())
	}) // cluster_handler.go:907
	cover96Call(func() { recv.clusterSecretHolders(zero96[http.ResponseWriter](), zero96[*http.Request]()) }) // cluster_handler.go:1823
	cover96Call(func() { recv.clusterTemplateItemWrap(zero96[http.Handler]()) })                              // template.go:169
	cover96Call(func() {
		recv.createSandboxOnSelectedNode(zero96[http.ResponseWriter](), zero96[*http.Request](), zero96[models.CreateSandboxRequest](), zero96[string]())
	}) // cluster_handler.go:195
	cover96Call(func() { recv.listSandboxes(zero96[http.ResponseWriter](), zero96[*http.Request]()) })    // handlers.go:115
	cover96Call(func() { recv.pushWasmModule(zero96[http.ResponseWriter](), zero96[*http.Request]()) })   // wasm_module.go:30
	cover96Call(func() { recv.registerSnapshot(zero96[http.ResponseWriter](), zero96[*http.Request]()) }) // snapshot.go:47
	cover96Call(func() { recv.resolveSnapshotImage(cover96Ctx(), zero96[string](), zero96[[]string]()) }) // snapshot.go:112
	cover96Call(func() {
		recv.runImageBuildOnTarget(zero96[cluster.Client](), zero96[*http.Request](), zero96[[]byte](), zero96[cluster.Member](), zero96[bool]())
	}) // build.go:136
	cover96Call(func() { recv.setNodeDrainState(zero96[http.ResponseWriter](), zero96[*http.Request](), zero96[bool]()) }) // cluster_handler.go:1020
	cover96Call(func() { recv.updateNetworkLimits(zero96[http.ResponseWriter](), zero96[*http.Request]()) })               // handlers.go:420
	cover96Call(func() { recv.writeOverlapCreateError(zero96[http.ResponseWriter](), zero96[error]()) })                   // cluster_handler.go:284
}

func cover96_funcs() {
	cover96Call(func() { acquireClusterListSlot(cover96Ctx()) })                                   // cluster_list.go:74
	cover96Call(func() { clusterOperatorAccess(zero96[*http.Request]()) })                         // cluster_handler.go:1000
	cover96Call(func() { clusterOperatorActor(zero96[*http.Request]()) })                          // cluster_handler.go:1008
	cover96Call(func() { dialClusterPeer(zero96[cluster.Client](), zero96[cluster.Member]()) })    // cluster_helpers.go:15
	cover96Call(func() { diskGBForCapacity(zero96[int](), zero96[string](), zero96[int]()) })      // cluster_handler.go:1946
	cover96Call(func() { parseRepeatedIntQuery(zero96[*http.Request](), zero96[string]()) })       // cluster_handler.go:410
	cover96Call(func() { peerMemberAlive(zero96[Deps](), zero96[string]()) })                      // routes.go:240
	cover96Call(func() { singleLineFROM(zero96[string]()) })                                       // snapshot.go:188
	cover96Call(func() { templateListKey(zero96[*models.Template]()) })                            // template.go:118
	cover96Call(func() { templateMemberByID(zero96[cluster.Client](), zero96[string]()) })         // template.go:153
	cover96Call(func() { templateOwnerFromInventory(zero96[cluster.Client](), zero96[string]()) }) // template.go:240
	cover96Call(func() {
		templatePeerRequest(zero96[cluster.Client](), zero96[*http.Request](), zero96[[]byte](), zero96[cluster.Member]())
	}) // template.go:306
	cover96Call(func() { writeAuditRateLimited(zero96[http.ResponseWriter](), zero96[time.Duration]()) }) // audit_limit.go:123
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_AuditRateLimiter *AuditRateLimiter
	recvptr_AuditRateLimiter = new(AuditRateLimiter)
	cover96_ptr_AuditRateLimiter(recvptr_AuditRateLimiter)
	var recvptr_handlers *handlers
	recvptr_handlers = new(handlers)
	cover96_ptr_handlers(recvptr_handlers)
	cover96_funcs()
}
