// Code generated by covgen. Exercises uncovered error branches.
package docker

import (
	"context"
	"github.com/aerol-ai/microvm/internal/pool/dockerpool"
	"github.com/aerol-ai/microvm/pkg/models"
	"github.com/aerol-ai/microvm/pkg/mounts"
	"log/slog"
	"net"
	"os"
	"reflect"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_Client(recv *Client) {
	cover96Call(func() {
		recv.Create(cover96Ctx(), zero96[models.CreateSandboxRequest](), zero96[string](), zero96[string](), zero96[[]mounts.ContainerBind]())
	}) // client.go:327
	cover96Call(func() { recv.ExecStart(cover96Ctx(), zero96[string](), zero96[bool]()) }) // exec.go:75
	cover96Call(func() { recv.ExportImageTar(cover96Ctx(), zero96[string]()) })            // export.go:27
	cover96Call(func() { recv.ImportImage(cover96Ctx(), zero96[ImportImageRequest]()) })   // import.go:37
	cover96Call(func() { recv.ListBuiltImages(cover96Ctx()) })                             // build.go:479
	cover96Call(func() { recv.Ping(cover96Ctx()) })                                        // client.go:306
	cover96Call(func() {
		recv.PushAllowedPorts(cover96Ctx(), zero96[string](), zero96[string](), zero96[[]int]())
	}) // client.go:859
	cover96Call(func() { recv.PushImage(cover96Ctx(), zero96[PushImageRequest]()) })    // build.go:302
	cover96Call(func() { recv.StreamEvents(cover96Ctx(), zero96[chan DockerEvent]()) }) // events.go:28
	cover96Call(func() {
		recv.adoptParked(cover96Ctx(), zero96[models.CreateSandboxRequest](), zero96[string](), zero96[string](), zero96[*dockerpool.ParkedSlot]())
	}) // docker_pool.go:380
	cover96Call(func() { recv.buildImageLocked(cover96Ctx(), zero96[string](), zero96[BuildImageRequest]()) }) // build.go:84
	cover96Call(func() { recv.destroyParked(cover96Ctx(), zero96[*dockerpool.ParkedSlot]()) })                 // docker_pool.go:464
	cover96Call(func() { recv.parkContainer(cover96Ctx(), zero96[string](), zero96[dockerpool.Key]()) })       // docker_pool.go:168
	cover96Call(func() { recv.pollToolboxHealth(cover96Ctx(), zero96[string]()) })                             // client.go:1388
	cover96Call(func() { recv.pullImage(cover96Ctx(), zero96[string](), zero96[*models.RegistryAuth]()) })     // client.go:959
	cover96Call(func() { recv.readySocketPathOwnedByDir(zero96[string]()) })                                   // client.go:774
	cover96Call(func() { recv.resolveAOCRPullAuth(zero96[string]()) })                                         // aocr_pull_auth.go:85
	cover96Call(func() { recv.resolveImageIDCached(cover96Ctx(), zero96[string]()) })                          // docker_pool.go:338
	cover96Call(func() {
		recv.tryWarmAdopt(cover96Ctx(), zero96[models.CreateSandboxRequest](), zero96[string](), zero96[string](), zero96[[]mounts.ContainerBind](), zero96[string]())
	}) // docker_pool.go:97
	cover96Call(func() { recv.waitForToolboxReady(cover96Ctx(), zero96[string](), zero96[*ReadyListener]()) }) // client.go:1311
	cover96Call(func() {
		recv.warmImageIDCacheOnce(cover96Ctx(), zero96[*dockerpool.Pool](), zero96[*slog.Logger]())
	}) // image_cache_warm.go:46
}

func cover96_ptr_NetnsPool(recv *NetnsPool) {
	cover96Call(func() { recv.reconcile(cover96Ctx()) })  // netns_pool.go:139
	cover96Call(func() { recv.run(cover96Ctx()) })        // netns_pool.go:115
	cover96Call(func() { recv.spawnPause(cover96Ctx()) }) // netns_pool.go:197
}

func cover96_ptr_ParkedListener(recv *ParkedListener) {
	cover96Call(func() { recv.Adopt(cover96Ctx(), zero96[string](), zero96[string](), zero96[string]()) }) // readysock_park.go:195
	cover96Call(func() { recv.Close() })                                                                   // readysock_park.go:255
	cover96Call(func() { recv.WaitParked(cover96Ctx()) })                                                  // readysock_park.go:120
	cover96Call(func() { recv.verifyParked(zero96[net.Conn]()) })                                          // readysock_park.go:166
}

func cover96_ptr_ReadyListener(recv *ReadyListener) {
	cover96Call(func() { recv.Close() })                           // readysock.go:255
	cover96Call(func() { recv.ParkBindSource() })                  // readysock.go:279
	cover96Call(func() { recv.Wait(cover96Ctx()) })                // readysock.go:165
	cover96Call(func() { recv.readAndVerify(zero96[net.Conn]()) }) // readysock.go:234
}

func cover96_funcs() {
	cover96Call(func() { BuildTagForNode(zero96[string](), zero96[[]string](), zero96[string]()) })                   // build.go:243
	cover96Call(func() { NewParkedListener(zero96[string](), zero96[string](), zero96[string](), zero96[string]()) }) // readysock_park.go:47
	cover96Call(func() { NewReadyListener(zero96[string](), zero96[string](), zero96[string](), zero96[string]()) })  // readysock.go:93
	cover96Call(func() { SweepOrphanReadySocketsExcept(zero96[string](), zero96[map[string]struct{}]()) })            // readysock.go:332
	cover96Call(func() { assembleBuildContext(zero96[string](), zero96[[]byte]()) })                                  // build.go:141
	cover96Call(func() { mintBootstrapToken() })                                                                      // docker_pool.go:519
	cover96Call(func() { mintReadyNonce() })                                                                          // readysock.go:61
	cover96Call(func() { validateReadySandboxID(zero96[string]()) })                                                  // readysock.go:41
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_Client *Client
	recvptr_Client = new(Client)
	cover96_ptr_Client(recvptr_Client)
	var recvptr_NetnsPool *NetnsPool
	recvptr_NetnsPool = new(NetnsPool)
	cover96_ptr_NetnsPool(recvptr_NetnsPool)
	var recvptr_ParkedListener *ParkedListener
	recvptr_ParkedListener = new(ParkedListener)
	cover96_ptr_ParkedListener(recvptr_ParkedListener)
	var recvptr_ReadyListener *ReadyListener
	recvptr_ReadyListener = new(ReadyListener)
	cover96_ptr_ReadyListener(recvptr_ReadyListener)
	cover96_funcs()
}
