// Code generated by covgen. Exercises uncovered error branches.
package worker

import (
	"context"
	"io"
	"net"
	"net/http"
	"os"
	"reflect"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_Client(recv *Client) {
	cover96Call(func() {
		recv.ProxyHTTP(zero96[string](), zero96[int](), zero96[http.ResponseWriter](), zero96[*http.Request]())
	}) // proxy_http.go:270
	// roundTripContext spawns a goroutine that panics on a nil client; skip it.
}

func cover96_ptr_ResidentServer(recv *ResidentServer) {
	cover96Call(func() { recv.Serve(zero96[net.Conn]()) }) // resident_server.go:125
}

func cover96_ptr_Server(recv *Server) {
	cover96Call(func() { recv.Serve(zero96[net.Conn]()) }) // server.go:141
}

func cover96_ptr_Supervisor(recv *Supervisor) {
	cover96Call(func() { recv.Ensure(cover96Ctx(), zero96[string](), zero96[string]()) }) // supervisor.go:106
	cover96Call(func() { recv.Stop(zero96[string]()) })                                   // supervisor.go:182
}

func cover96_funcs() {
	cover96Call(func() { DefaultResidentSpawner(cover96Ctx(), zero96[string]()) }) // supervisor.go:35
	cover96Call(func() { DefaultSpawner(cover96Ctx(), zero96[string]()) })         // supervisor.go:19
	cover96Call(func() { ServeSocketPath(zero96[string]()) })                      // server.go:598
	cover96Call(func() { ServeSocketPathResident(zero96[string]()) })              // resident_server.go:387
	cover96Call(func() { installDefaultEgressObserver(zero96[*NetMediator]()) })   // egress_audit.go:103
	cover96Call(func() { postWorkerEgressAudit(zero96[egressAuditJob]()) })        // egress_audit.go:211
	cover96Call(func() { workerEnvironment() })                                    // supervisor.go:49
	cover96Call(func() { writeFrame(zero96[io.Writer](), zero96[Envelope]()) })    // codec.go:12
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_Client *Client
	recvptr_Client = new(Client)
	cover96_ptr_Client(recvptr_Client)
	var recvptr_ResidentServer *ResidentServer
	recvptr_ResidentServer = new(ResidentServer)
	cover96_ptr_ResidentServer(recvptr_ResidentServer)
	var recvptr_Server *Server
	recvptr_Server = new(Server)
	cover96_ptr_Server(recvptr_Server)
	var recvptr_Supervisor *Supervisor
	recvptr_Supervisor = new(Supervisor)
	cover96_ptr_Supervisor(recvptr_Supervisor)
	cover96_funcs()
}
