// Code generated by covgen. Exercises uncovered error branches.
package daytona

import (
	"context"
	"github.com/aerol-ai/microvm/pkg/models"
	"mime/multipart"
	"net/http"
	"os"
	"reflect"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_handlers(recv *handlers) {
	cover96Call(func() { recv.bulkUpload(zero96[http.ResponseWriter](), zero96[*http.Request](), zero96[string]()) }) // toolbox.go:171
	cover96Call(func() { recv.createSandbox(zero96[http.ResponseWriter](), zero96[*http.Request]()) })                // handlers.go:39
	cover96Call(func() { recv.getSandbox(zero96[http.ResponseWriter](), zero96[*http.Request]()) })                   // handlers.go:520
	cover96Call(func() { recv.hydrateEnvIfRequested(zero96[*http.Request](), zero96[*models.Sandbox]()) })            // handlers.go:802
	cover96Call(func() { recv.listSandboxes(zero96[http.ResponseWriter](), zero96[*http.Request]()) })                // handlers.go:395
	cover96Call(func() { recv.listSandboxesPaginated(zero96[http.ResponseWriter](), zero96[*http.Request]()) })       // handlers.go:427
	cover96Call(func() { recv.persistSandboxMeta(cover96Ctx(), zero96[string](), zero96[sandboxMeta]()) })            // handlers.go:925
	cover96Call(func() { recv.replaceLabels(zero96[http.ResponseWriter](), zero96[*http.Request]()) })                // handlers.go:690
	cover96Call(func() { recv.resolveSandbox(cover96Ctx(), zero96[string]()) })                                       // handlers.go:826
	cover96Call(func() { recv.runToolboxCommand(cover96Ctx(), zero96[string](), zero96[models.ExecRequest]()) })      // toolbox.go:338
	cover96Call(func() { recv.runToolboxString(cover96Ctx(), zero96[string](), zero96[string]()) })                   // toolbox.go:326
	// skip sendToolboxJSON (toolbox.go:371)
	cover96Call(func() { recv.setAutoArchiveInterval(zero96[http.ResponseWriter](), zero96[*http.Request]()) }) // handlers.go:719
	cover96Call(func() { recv.translateCreateSandboxRequest(cover96Ctx(), zero96[createSandboxRequest]()) })    // handlers.go:1164
	cover96Call(func() {
		recv.updateIdleLifecycle(zero96[http.ResponseWriter](), zero96[*http.Request](), zero96[bool]())
	}) // handlers.go:748
	cover96Call(func() {
		recv.uploadSingleFile(cover96Ctx(), zero96[string](), zero96[string](), zero96[*multipart.FileHeader]())
	}) // toolbox.go:283
}

func cover96_funcs() {
	cover96Call(func() { parseListFilters(zero96[*http.Request]()) })                              // handlers.go:978
	cover96Call(func() { readToolboxHTTPError(zero96[*http.Response]()) })                         // toolbox.go:415
	cover96Call(func() { sandboxMetaFromNative(zero96[*models.Sandbox](), zero96[compatBlob]()) }) // meta.go:51
	cover96Call(func() { sandboxMetaToState(zero96[sandboxMeta]()) })                              // meta.go:90
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_handlers *handlers
	recvptr_handlers = new(handlers)
	cover96_ptr_handlers(recvptr_handlers)
	cover96_funcs()
}
