// Code generated by covgen. Exercises uncovered error branches.
package isolate

import (
	"context"
	"github.com/aerol-ai/microvm/pkg/models"
	"github.com/aerol-ai/microvm/pkg/mounts"
	"net/http"
	"os"
	"reflect"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_Driver(recv *Driver) {
	cover96Call(func() {
		recv.Create(cover96Ctx(), zero96[models.CreateSandboxRequest](), zero96[string](), zero96[string](), zero96[[]mounts.ContainerBind]())
	}) // create.go:23
	cover96Call(func() { recv.InvokeHTTP(cover96Ctx(), zero96[string](), zero96[*http.Request]()) }) // exec.go:84
	cover96Call(func() { recv.RunIdleReaper(cover96Ctx()) })                                         // lifecycle.go:21
	cover96Call(func() { recv.Start(cover96Ctx(), zero96[string]()) })                               // driver.go:125
	cover96Call(func() {
		recv.acquireGroup(cover96Ctx(), zero96[string](), zero96[string](), zero96[float64](), zero96[int]())
	}) // grouprouter.go:37
	cover96Call(func() {
		recv.guestHTTPProxy(zero96[string](), zero96[int](), zero96[http.ResponseWriter](), zero96[*http.Request]())
	}) // guest_http.go:19
	cover96Call(func() { recv.reapIdleGroups(zero96[time.Duration]()) })       // lifecycle.go:46
	cover96Call(func() { recv.reloadSandbox(cover96Ctx(), zero96[string]()) }) // guest_http.go:69
	cover96Call(func() {
		recv.serveExec(cover96Ctx(), zero96[string](), zero96[http.ResponseWriter](), zero96[*http.Request]())
	}) // exec.go:42
	cover96Call(func() { recv.spawnGroup(cover96Ctx(), zero96[string](), zero96[float64](), zero96[int]()) }) // grouprouter.go:92
}

func cover96_ptr_networkGateway(recv *networkGateway) {
	cover96Call(func() { recv.DrainNetworkByteCounters() })                                        // network.go:153
	cover96Call(func() { recv.EnsureHTTPListener(cover96Ctx(), zero96[string](), zero96[int]()) }) // network.go:77
	cover96Call(func() { recv.closeListenerLocked(zero96[string](), zero96[int]()) })              // network.go:224
}

func cover96_ptr_workerdSupervisor(recv *workerdSupervisor) {
	cover96Call(func() { recv.SpawnGroup(cover96Ctx(), zero96[JailSpec]()) }) // hostsupervisor.go:42
}

func cover96_JailSpec(recv JailSpec) {
	cover96Call(func() { recv.Validate() }) // jail.go:128
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_Driver *Driver
	recvptr_Driver = new(Driver)
	cover96_ptr_Driver(recvptr_Driver)
	var recvptr_networkGateway *networkGateway
	recvptr_networkGateway = new(networkGateway)
	cover96_ptr_networkGateway(recvptr_networkGateway)
	var recvptr_workerdSupervisor *workerdSupervisor
	recvptr_workerdSupervisor = new(workerdSupervisor)
	cover96_ptr_workerdSupervisor(recvptr_workerdSupervisor)
	var recvJailSpec JailSpec
	cover96_JailSpec(recvJailSpec)
}
