// Code generated by covgen. Exercises uncovered error branches.
package store

import (
	"context"
	"database/sql"
	"github.com/aerol-ai/microvm/pkg/auditlog"
	"github.com/aerol-ai/microvm/pkg/models"
	"github.com/aerol-ai/microvm/pkg/secrets"
	"os"
	"reflect"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_SecretAuditIndexChunk(recv *SecretAuditIndexChunk) {
	cover96Call(func() { recv.Append(zero96[[]auditlog.IndexEntry]()) }) // secret_audit_index.go:88
}

func cover96_ptr_Store(recv *Store) {
	cover96Call(func() { recv.AddCustomDomain(cover96Ctx(), zero96[string](), zero96[string](), zero96[int]()) }) // store.go:4181
	cover96Call(func() { recv.AllocateFirecrackerTapSlot(cover96Ctx(), zero96[string](), zero96[time.Time]()) })  // store.go:6937
	cover96Call(func() {
		recv.AllocateFirecrackerVMMSlot(cover96Ctx(), zero96[string](), zero96[string](), zero96[time.Time]())
	}) // store.go:7327
	cover96Call(func() { recv.BeginPrewarmContainerNetnsSlot(cover96Ctx(), zero96[time.Time]()) }) // netns_slots.go:123
	cover96Call(func() {
		recv.ClaimIdempotentRequest(cover96Ctx(), zero96[string](), zero96[string](), zero96[time.Time](), zero96[time.Duration]())
	}) // store.go:2969
	cover96Call(func() {
		recv.ClaimPooledContainerNetnsSlot(cover96Ctx(), zero96[string](), zero96[time.Time]())
	}) // netns_slots.go:198
	cover96Call(func() { recv.ClusterSecretSealSummaries(cover96Ctx(), zero96[[]string]()) }) // store.go:6060
	cover96Call(func() {
		recv.ClusterSecretTombGenerationForIncarnation(cover96Ctx(), zero96[string](), zero96[string]())
	}) // store.go:6699
	cover96Call(func() { recv.Create(cover96Ctx(), zero96[*models.Sandbox]()) })                                // store.go:1448
	cover96Call(func() { recv.CreateSnapshot(cover96Ctx(), zero96[*models.SandboxSnapshot]()) })                // store.go:3110
	cover96Call(func() { recv.CreateWithSealedEnv(cover96Ctx(), zero96[*models.Sandbox](), zero96[[]byte]()) }) // store.go:1486
	cover96Call(func() { recv.CurrentSandboxAuditIdentity(cover96Ctx(), zero96[string]()) })                    // store.go:8408
	cover96Call(func() {
		recv.DeleteClusterSecretsOriginatorWithOutbox(cover96Ctx(), zero96[string](), zero96[string](), zero96[[]string]())
	}) // store.go:5687
	cover96Call(func() { recv.DeleteFirecrackerVMMSlot(cover96Ctx(), zero96[string]()) })    // store.go:7546
	cover96Call(func() { recv.DeleteNodeStorageRetirement(cover96Ctx(), zero96[string]()) }) // store.go:8466
	cover96Call(func() { recv.DeleteOrphanedWasmStateKV(cover96Ctx(), zero96[int]()) })      // store.go:7829
	cover96Call(func() {
		recv.DeletePendingImageGCIfScheduledAt(cover96Ctx(), zero96[string](), zero96[string](), zero96[time.Time]())
	}) // store.go:2396
	cover96Call(func() {
		recv.DeleteSecretDeleteOutbox(cover96Ctx(), zero96[string](), zero96[string](), zero96[int64]())
	}) // store.go:6302
	cover96Call(func() { recv.DeleteVolume(cover96Ctx(), zero96[string](), zero96[string]()) }) // volumes.go:231
	cover96Call(func() {
		recv.DeleteVolumeIfUnattached(cover96Ctx(), zero96[string](), zero96[string](), zero96[string]())
	}) // volumes.go:353
	cover96Call(func() { recv.EnsureWasmCheckpointCleanupRef(cover96Ctx(), zero96[string](), zero96[string]()) }) // store.go:7909
	cover96Call(func() {
		recv.FinishPrewarmContainerNetnsSlot(cover96Ctx(), zero96[string](), zero96[string](), zero96[string](), zero96[time.Time]())
	}) // netns_slots.go:170
	cover96Call(func() { recv.GetEnvWithIdentity(cover96Ctx(), zero96[string]()) })                       // store.go:6827
	cover96Call(func() { recv.GetFirecrackerVMMPoolStats(cover96Ctx(), zero96[string]()) })               // store.go:7569
	cover96Call(func() { recv.GetOrCreateVolume(cover96Ctx(), zero96[*models.Volume](), zero96[int]()) }) // volumes.go:72
	cover96Call(func() {
		recv.GetSecretDeleteOutboxForIncarnation(cover96Ctx(), zero96[string](), zero96[string]())
	}) // store.go:5770
	cover96Call(func() { recv.HasSandboxAuditACL(cover96Ctx(), zero96[string](), zero96[string]()) }) // store.go:5318
	cover96Call(func() {
		recv.InsertWasmCheckpointPush(cover96Ctx(), zero96[string](), zero96[string](), zero96[string](), zero96[string]())
	}) // store.go:7890
	cover96Call(func() { recv.LatestSecretAuditIndexChunks(cover96Ctx(), zero96[[]SecretAuditIndexKey]()) }) // secret_audit_index.go:211
	cover96Call(func() { recv.List(cover96Ctx()) })                                                          // store.go:1986
	cover96Call(func() { recv.ListAllCustomDomains(cover96Ctx()) })                                          // store.go:4281
	cover96Call(func() { recv.ListAllExposedPorts(cover96Ctx()) })                                           // store.go:4115
	cover96Call(func() { recv.ListAutoImportPendingIDs(cover96Ctx()) })                                      // store.go:2645
	cover96Call(func() { recv.ListByOwner(cover96Ctx(), zero96[string]()) })                                 // store.go:2054
	cover96Call(func() { recv.ListByRuntime(cover96Ctx(), zero96[string]()) })                               // store.go:2107
	cover96Call(func() { recv.ListClusterSecretsBatch(cover96Ctx(), zero96[string](), zero96[int]()) })      // store.go:6722
	cover96Call(func() { recv.ListCompatState(cover96Ctx(), zero96[string]()) })                             // store.go:2795
	cover96Call(func() { recv.ListCustomDomains(cover96Ctx(), zero96[string]()) })                           // store.go:4250
	cover96Call(func() { recv.ListGCEligibleTemplates(cover96Ctx(), zero96[time.Time]()) })                  // store.go:3836
	cover96Call(func() { recv.ListNodeStorageRetirements(cover96Ctx()) })                                    // store.go:8485
	cover96Call(func() { recv.ListPendingImageGCDue(cover96Ctx(), zero96[time.Time](), zero96[int]()) })     // store.go:2302
	cover96Call(func() { recv.ListPendingVolumeDeletions(cover96Ctx()) })                                    // volumes.go:427
	cover96Call(func() { recv.ListReadyWasmModuleRefs(cover96Ctx()) })                                       // store.go:8155
	cover96Call(func() { recv.ListSnapshotAliases(cover96Ctx(), zero96[string]()) })                         // store.go:2901
	cover96Call(func() { recv.ListSnapshots(cover96Ctx()) })                                                 // store.go:3176
	cover96Call(func() { recv.ListSnapshotsPendingPush(cover96Ctx()) })                                      // store.go:3886
	cover96Call(func() { recv.ListTemplateInventoryIDs(cover96Ctx()) })                                      // store.go:3665
	cover96Call(func() { recv.ListTemplates(cover96Ctx()) })                                                 // store.go:3314
	cover96Call(func() { recv.ListTemplatesPendingPush(cover96Ctx()) })                                      // store.go:3542
	cover96Call(func() { recv.ListTemplatesReadyBefore(cover96Ctx(), zero96[time.Time]()) })                 // store.go:3629
	cover96Call(func() { recv.ListUnhealthyTemplates(cover96Ctx()) })                                        // store.go:3590
	cover96Call(func() { recv.ListVolumes(cover96Ctx(), zero96[string]()) })                                 // volumes.go:188
	cover96Call(func() { recv.ListWasmStateKVKeys(cover96Ctx(), zero96[string]()) })                         // store.go:7853
	cover96Call(func() {
		recv.MarkFirecrackerVMMSlotFailed(cover96Ctx(), zero96[string](), zero96[string](), zero96[time.Time]())
	}) // store.go:7283
	cover96Call(func() {
		recv.MarkFirecrackerVMMSlotLoaded(cover96Ctx(), zero96[string](), zero96[string](), zero96[string](), zero96[uint32](), zero96[time.Time]())
	}) // store.go:7242
	cover96Call(func() {
		recv.MarkSecretDeleteOutboxPromoted(cover96Ctx(), zero96[string](), zero96[string](), zero96[int64]())
	}) // store.go:5659
	cover96Call(func() { recv.MarkTemplatePushPending(cover96Ctx(), zero96[string]()) })                 // store.go:3510
	cover96Call(func() { recv.MarkTemplateUnhealthy(cover96Ctx(), zero96[string](), zero96[string]()) }) // store.go:3476
	cover96Call(func() {
		recv.NextClusterSecretSealGenerationForIncarnation(cover96Ctx(), zero96[string](), zero96[string]())
	}) // store.go:5987
	cover96Call(func() { recv.PruneClusterSecretTombs(cover96Ctx(), zero96[time.Time](), zero96[int]()) }) // store.go:6656
	cover96Call(func() { recv.PruneSandboxAuditACL(cover96Ctx(), zero96[time.Time]()) })                   // store.go:5270
	cover96Call(func() { recv.PutClusterSecret(cover96Ctx(), zero96[ClusterSecretRecord]()) })             // store.go:4879
	cover96Call(func() {
		recv.PutNodeStorageRetirement(cover96Ctx(), zero96[string](), zero96[string](), zero96[string](), zero96[time.Time]())
	}) // store.go:8440
	cover96Call(func() { recv.PutVolumeAttachments(cover96Ctx(), zero96[[]models.VolumeAttachment]()) }) // volumes.go:252
	cover96Call(func() {
		recv.ReadSecretAuditIndex(cover96Ctx(), zero96[SecretAuditIndexKey](), zero96[int64]())
	}) // secret_audit_index.go:304
	cover96Call(func() {
		recv.ReassignContainerNetnsSandbox(cover96Ctx(), zero96[string](), zero96[string](), zero96[time.Time]())
	}) // netns_slots.go:381
	cover96Call(func() {
		recv.RefreshPendingImageGCIfExists(cover96Ctx(), zero96[string](), zero96[time.Time]())
	}) // store.go:2365
	cover96Call(func() { recv.ReleaseOrphanedFirecrackerVMMSlots(cover96Ctx(), zero96[time.Time]()) })          // store.go:7411
	cover96Call(func() { recv.ReserveContainerNetnsSlot(cover96Ctx(), zero96[string](), zero96[time.Time]()) }) // netns_slots.go:56
	cover96Call(func() { recv.ResetSecretAuditIndex(cover96Ctx(), zero96[SecretAuditIndexMeta]()) })            // secret_audit_index.go:188
	cover96Call(func() { recv.RollbackSandboxCreate(cover96Ctx(), zero96[string](), zero96[string]()) })        // store.go:2684
	cover96Call(func() { recv.SandboxAuditIncarnations(cover96Ctx(), zero96[[]string]()) })                     // store.go:5343
	cover96Call(func() { recv.SecretDeleteOwedByRecipient(cover96Ctx()) })                                      // store.go:6144
	cover96Call(func() { recv.SecretLifecycleStats(cover96Ctx()) })                                             // store.go:6602
	cover96Call(func() { recv.SetFleetSuspended(cover96Ctx(), zero96[string](), zero96[bool]()) })              // store.go:2158
	cover96Call(func() {
		recv.ShiftSecretAuditIndex(cover96Ctx(), zero96[int64](), zero96[int64](), zero96[SecretAuditIndexMeta]())
	}) // secret_audit_index.go:353
	cover96Call(func() {
		recv.TransferFirecrackerTapSlot(cover96Ctx(), zero96[string](), zero96[string](), zero96[time.Time]())
	}) // store.go:7022
	cover96Call(func() {
		recv.TryReserveHostPort(cover96Ctx(), zero96[string](), zero96[int](), zero96[int](), zero96[string](), zero96[string](), zero96[time.Time]())
	}) // store.go:4048
	cover96Call(func() {
		recv.UpdateSecretDeleteOutboxRecipients(cover96Ctx(), zero96[string](), zero96[string](), zero96[[]string](), zero96[int64]())
	}) // store.go:5805
	cover96Call(func() {
		recv.UpdateSecretPutOutboxRecipients(cover96Ctx(), zero96[string](), zero96[string](), zero96[[]string](), zero96[int64]())
	}) // store.go:6495
	cover96Call(func() { recv.UpdateTags(cover96Ctx(), zero96[string](), zero96[map[string]string]()) }) // store.go:2418
	cover96Call(func() {
		recv.UpdateWasmCheckpoint(cover96Ctx(), zero96[string](), zero96[string](), zero96[string](), zero96[string](), zero96[string](), zero96[string]())
	}) // store.go:7741
	cover96Call(func() {
		recv.UpdateWasmRegistryPush(cover96Ctx(), zero96[string](), zero96[string](), zero96[string](), zero96[string]())
	}) // store.go:8133
	cover96Call(func() { recv.Upsert(cover96Ctx(), zero96[*models.Sandbox]()) }) // store.go:1723
	cover96Call(func() {
		recv.UpsertSandboxAuditACL(cover96Ctx(), zero96[string](), zero96[string](), zero96[string]())
	}) // store.go:5194
	cover96Call(func() {
		recv.UpsertSecretDeleteOutboxCopiedAt(cover96Ctx(), zero96[string](), zero96[string](), zero96[[]string](), zero96[int64](), zero96[time.Time]())
	}) // store.go:5473
	cover96Call(func() {
		recv.UpsertSecretPutOutbox(cover96Ctx(), zero96[string](), zero96[string](), zero96[int64](), zero96[[]string]())
	}) // store.go:6339
	cover96Call(func() { recv.UpsertSnapshotAlias(cover96Ctx(), zero96[models.SnapshotAlias]()) }) // store.go:2843
	cover96Call(func() {
		recv.WasmCheckpointRefInUse(cover96Ctx(), zero96[string](), zero96[int64](), zero96[string](), zero96[string](), zero96[string]())
	}) // store.go:8062
	cover96Call(func() { recv.WasmDigestsInUse(cover96Ctx(), zero96[[]string]()) }) // store.go:8251
	cover96Call(func() {
		recv.WriteSecretAuditIndex(cover96Ctx(), zero96[SecretAuditIndexMeta](), zero96[SecretAuditIndexMeta](), zero96[[]SecretAuditIndexChunk]())
	}) // secret_audit_index.go:246
	cover96Call(func() {
		recv.applySecretDelete(cover96Ctx(), zero96[string](), zero96[string](), zero96[int64](), zero96[bool]())
	}) // store.go:5903
	cover96Call(func() { recv.attachCustomDomainsBulk(cover96Ctx(), zero96[map[string]*models.Sandbox]()) }) // store.go:4368
	cover96Call(func() { recv.attachPortsBulk(cover96Ctx(), zero96[map[string]*models.Sandbox]()) })         // store.go:2207
	cover96Call(func() { recv.insertSandbox(cover96Ctx(), zero96[dbExecer](), zero96[*models.Sandbox]()) })  // store.go:1518
	cover96Call(func() {
		recv.listSecretDeleteOutbox(cover96Ctx(), zero96[string](), zero96[[]any](), zero96[int]())
	}) // store.go:6179
	cover96Call(func() {
		recv.listSecretPutOutbox(cover96Ctx(), zero96[string](), zero96[[]any](), zero96[int]())
	}) // store.go:6461
	cover96Call(func() { recv.loadPorts(cover96Ctx(), zero96[string]()) })                 // store.go:4397
	cover96Call(func() { recv.openToolboxToken(zero96[*models.Sandbox]()) })               // store.go:1670
	cover96Call(func() { recv.queryWasmCheckpointPushes(cover96Ctx(), zero96[string]()) }) // store.go:7976
	cover96Call(func() {
		recv.retrySecretDeleteOutbox(cover96Ctx(), zero96[string](), zero96[string](), zero96[int64](), zero96[bool]())
	}) // store.go:6277
	cover96Call(func() { recv.toolboxTokenStorage(zero96[*models.Sandbox]()) }) // store.go:1688
}

func cover96_funcs() {
	cover96Call(func() {
		NewSecretAuditIndexChunk(zero96[SecretAuditIndexKey](), zero96[int64](), zero96[[]auditlog.IndexEntry]())
	}) // secret_audit_index.go:72
	cover96Call(func() { applyPutOutboxInTx(cover96Ctx(), zero96[*sql.Tx](), zero96[ClusterSecretRecord]()) }) // store.go:5066
	cover96Call(func() { checkpointRefTag(zero96[string]()) })                                                 // store.go:8024
	cover96Call(func() {
		clusterSecretCopiedAtTx(cover96Ctx(), zero96[*sql.Tx](), zero96[string](), zero96[string]())
	}) // store.go:5049
	cover96Call(func() { collectFirecrackerVMMSlots(zero96[*sql.Rows]()) })                                        // store.go:7645
	cover96Call(func() { envIncarnationForMigration(cover96Ctx(), zero96[*sql.Tx](), zero96[string]()) })          // env_binding_migration.go:104
	cover96Call(func() { inspectLegacySecretColumns(zero96[*sql.DB]()) })                                          // store.go:1095
	cover96Call(func() { marshalGPUs(zero96[*models.GPURequest]()) })                                              // store.go:4740
	cover96Call(func() { mergeSecretDeleteProvenance(zero96[string](), zero96[[]string](), zero96[time.Time]()) }) // store.go:5619
	cover96Call(func() { migrateEnvBinding(zero96[*sql.DB](), zero96[*secrets.Cipher]()) })                        // env_binding_migration.go:16
	cover96Call(func() {
		migrateLegacyEnvRows(cover96Ctx(), zero96[*sql.Tx](), zero96[*secrets.Cipher](), zero96[time.Time]())
	}) // store.go:1123
	cover96Call(func() { migrateLegacyPlaintextSecrets(zero96[*sql.DB](), zero96[*secrets.Cipher]()) }) // store.go:1016
	cover96Call(func() {
		migrateLegacyToolboxTokenRows(cover96Ctx(), zero96[*sql.Tx](), zero96[*secrets.Cipher]())
	}) // store.go:1254
	cover96Call(func() { migratePendingImageGCKey(zero96[*sql.DB]()) }) // store.go:1197
	cover96Call(func() { mustMarshalStringSlice(zero96[[]string]()) })  // store.go:1641
	// skip open (store.go:52)
	cover96Call(func() { retainSecretDeleteProvenance(zero96[string](), zero96[[]string]()) }) // store.go:5870
	// skip scanFirecrackerVMMSlot (store.go:7614)
	cover96Call(func() {
		upsertSecretDeleteOutboxTx(cover96Ctx(), zero96[*sql.Tx](), zero96[string](), zero96[string](), zero96[[]string](), zero96[[]string](), zero96[int64](), zero96[bool](), zero96[time.Time]())
	}) // store.go:5500
	cover96Call(func() { validateCurrentSecretSchema(zero96[*sql.DB]()) })                                            // store.go:1313
	cover96Call(func() { validateRequiredTableShape(zero96[*sql.DB](), zero96[string](), zero96[map[string]int]()) }) // store.go:1391
	cover96Call(func() {
		writeSecretAuditIndexMeta(cover96Ctx(), zero96[dbExecer](), zero96[SecretAuditIndexMeta]())
	}) // secret_audit_index.go:163
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_SecretAuditIndexChunk *SecretAuditIndexChunk
	recvptr_SecretAuditIndexChunk = new(SecretAuditIndexChunk)
	cover96_ptr_SecretAuditIndexChunk(recvptr_SecretAuditIndexChunk)
	recvptr_Store := newTestStore(t)
	recvptr_Store.Close()
	cover96_ptr_Store(recvptr_Store)
	cover96_funcs()
}
