// Code generated by covgen. Exercises uncovered error branches.
package firecracker

import (
	"context"
	"github.com/aerol-ai/microvm/pkg/models"
	"github.com/aerol-ai/microvm/pkg/mounts"
	"os"
	"reflect"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_Driver(recv *Driver) {
	cover96Call(func() {
		recv.Create(cover96Ctx(), zero96[models.CreateSandboxRequest](), zero96[string](), zero96[string](), zero96[[]mounts.ContainerBind]())
	}) // driver.go:453
	cover96Call(func() { recv.SnapshotTemplate(cover96Ctx(), zero96[TemplateSnapshotRequest]()) }) // snapshot.go:76
	cover96Call(func() { recv.WarmSpawn(cover96Ctx(), zero96[WarmSpawnRequest]()) })               // warmspawn.go:99
	cover96Call(func() {
		recv.configureSandboxSnapshotRestore(cover96Ctx(), zero96[VMMClient](), zero96[*sandboxSnapshotManifest](), zero96[string](), zero96[string](), zero96[string](), zero96[*TapSlot](), zero96[string]())
	}) // sandbox_snapshot.go:463
	cover96Call(func() {
		recv.configureVMM(cover96Ctx(), zero96[VMMClient](), zero96[models.CreateSandboxRequest](), zero96[string](), zero96[*TapSlot](), zero96[string]())
	}) // driver.go:917
	cover96Call(func() {
		recv.configureVMMForLoad(cover96Ctx(), zero96[VMMClient](), zero96[*TemplateResolution](), zero96[string](), zero96[*TapSlot](), zero96[string]())
	}) // driver.go:1032
	cover96Call(func() {
		recv.probeToolboxTCP(cover96Ctx(), zero96[string](), zero96[string](), zero96[*TapSlot](), zero96[bool]())
	}) // driver.go:1124
	cover96Call(func() { recv.requireKernelVMGenID() }) // driver.go:1694
	// skip sendVsockOp (snapshot.go:392)
	cover96Call(func() { recv.startFromSandboxSnapshot(cover96Ctx(), zero96[string]()) }) // sandbox_snapshot.go:296
	cover96Call(func() { recv.stopToSandboxSnapshot(cover96Ctx(), zero96[string]()) })    // sandbox_snapshot.go:98
	cover96Call(func() {
		recv.tryAcquireWarm(cover96Ctx(), zero96[models.CreateSandboxRequest](), zero96[string](), zero96[*TemplateResolution](), zero96[string]())
	}) // warmacquire.go:94
	cover96Call(func() {
		recv.writeSandboxSnapshot(cover96Ctx(), zero96[string](), zero96[VMMHandle](), zero96[VMMClient](), zero96[uint32]())
	}) // sandbox_snapshot.go:187
}

func cover96_ptr_vmm(recv *vmm) {
	cover96Call(func() { recv.Kill() })                                            // vmm.go:348
	cover96Call(func() { recv.Shutdown(cover96Ctx(), zero96[time.Duration]()) })   // vmm.go:310
	cover96Call(func() { recv.Start(cover96Ctx()) })                               // vmm.go:153
	cover96Call(func() { recv.WaitSocket(cover96Ctx(), zero96[time.Duration]()) }) // vmm.go:246
}

func cover96_funcs() {
	cover96Call(func() { linkOrCopyRootfs(zero96[string](), zero96[string]()) }) // driver.go:1863
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_Driver *Driver
	recvptr_Driver = new(Driver)
	cover96_ptr_Driver(recvptr_Driver)
	var recvptr_vmm *vmm
	recvptr_vmm = new(vmm)
	cover96_ptr_vmm(recvptr_vmm)
	cover96_funcs()
}
