// Code generated by covgen. Exercises uncovered error branches.
package caddy

import (
	"context"
	"net/http"
	"os"
	"reflect"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_Client(recv *Client) {
	// skip Batch (batch.go:35)
	cover96Call(func() { recv.DeleteTCPRoute(cover96Ctx(), zero96[int]()) })                    // client.go:1242
	cover96Call(func() { recv.EnsureLayer4(cover96Ctx(), zero96[string](), zero96[string]()) }) // client.go:990
	cover96Call(func() {
		recv.EnsureOnDemandTLS(cover96Ctx(), zero96[string](), zero96[int](), zero96[time.Duration]())
	}) // client.go:884
	cover96Call(func() { recv.EnsureStaticIngressRoutes(cover96Ctx(), zero96[StaticRouteSpec]()) }) // static_routes.go:147
	cover96Call(func() { recv.PruneDynamicRoutes(cover96Ctx()) })                                   // static_routes.go:263
	cover96Call(func() { recv.RemoveStaticRoutes(cover96Ctx()) })                                   // static_routes.go:166
	cover96Call(func() { recv.Snapshot(cover96Ctx()) })                                             // client.go:1459
	cover96Call(func() {
		recv.UpsertSNIPassthroughRoute(cover96Ctx(), zero96[string](), zero96[string](), zero96[string](), zero96[int]())
	}) // client.go:1391
	cover96Call(func() {
		recv.UpsertTCPProxyRoute(cover96Ctx(), zero96[string](), zero96[int](), zero96[int](), zero96[string](), zero96[int]())
	}) // client.go:1206
	cover96Call(func() {
		recv.UpsertTCPRoute(cover96Ctx(), zero96[string](), zero96[string](), zero96[int](), zero96[int]())
	}) // client.go:1126
	cover96Call(func() {
		recv.UpsertTLSSNIRoute(cover96Ctx(), zero96[string](), zero96[string](), zero96[string](), zero96[int]())
	}) // client.go:1283
	cover96Call(func() {
		recv.UpsertWakeTCPRoute(cover96Ctx(), zero96[string](), zero96[int](), zero96[int](), zero96[string]())
	}) // client.go:1164
	cover96Call(func() {
		recv.UpsertWakeTLSSNIRoute(cover96Ctx(), zero96[string](), zero96[string](), zero96[string](), zero96[int]())
	}) // client.go:1335
	// skip ensureRouteAt (static_routes.go:184)
	cover96Call(func() { recv.fetchRawConfig(cover96Ctx()) })                                                   // batch.go:104
	cover96Call(func() { recv.getRouteList(cover96Ctx(), zero96[string]()) })                                   // static_routes.go:214
	cover96Call(func() { recv.hasOnDemandPolicy(cover96Ctx()) })                                                // client.go:940
	cover96Call(func() { recv.sendDirect(cover96Ctx(), zero96[string](), zero96[string](), zero96[[]byte]()) }) // batch.go:89
	cover96Call(func() {
		recv.sendJSONDetail(cover96Ctx(), zero96[string](), zero96[string](), zero96[[]byte]())
	}) // client.go:726
	cover96Call(func() { recv.upsertRoute(cover96Ctx(), zero96[string](), zero96[map[string]any]()) }) // client.go:582
}

func cover96_ptr_configEmulator(recv *configEmulator) {
	cover96Call(func() { recv.RoundTrip(zero96[*http.Request]()) }) // batch.go:159
	// skip apply (batch.go:193)
}

func cover96_funcs() {
	// skip NewConfigEmulator (batch.go:147)
	// skip setAt (batch.go:346)
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_Client *Client
	recvptr_Client = new(Client)
	cover96_ptr_Client(recvptr_Client)
	var recvptr_configEmulator *configEmulator
	recvptr_configEmulator = new(configEmulator)
	cover96_ptr_configEmulator(recvptr_configEmulator)
	cover96_funcs()
}
