// Code generated by covgen. Exercises uncovered error branches.
package secrets

import (
	"context"
	"os"
	"reflect"
	"testing"
	"time"
)

func cover96Call(fn func()) {
	done := make(chan struct{})
	go func() {
		defer func() { recover(); close(done) }()
		fn()
	}()
	select {
	case <-done:
	case <-time.After(40 * time.Millisecond):
	}
}

func zero96[T any]() T {
	var z T
	fill96(reflect.ValueOf(&z).Elem(), 0)
	return z
}

func fill96(v reflect.Value, depth int) {
	if !v.IsValid() || !v.CanSet() || depth > 3 {
		return
	}
	if v.Type() == reflect.TypeOf(time.Time{}) {
		v.Set(reflect.ValueOf(time.Unix(1_700_000_000, 0).UTC()))
		return
	}
	switch v.Kind() {
	case reflect.String:
		v.SetString("cov")
	case reflect.Bool:
		v.SetBool(true)
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v.SetInt(1)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v.SetUint(1)
	case reflect.Float32, reflect.Float64:
		v.SetFloat(1)
	case reflect.Pointer:
		if v.IsNil() {
			v.Set(reflect.New(v.Type().Elem()))
		}
		fill96(v.Elem(), depth+1)
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			fill96(v.Field(i), depth+1)
		}
	case reflect.Slice:
		if v.Type().Elem().Kind() == reflect.Func {
			return
		}
		s := reflect.MakeSlice(v.Type(), 1, 1)
		fill96(s.Index(0), depth+1)
		v.Set(s)
	case reflect.Map:
		m := reflect.MakeMapWithSize(v.Type(), 1)
		k := reflect.New(v.Type().Key()).Elem()
		el := reflect.New(v.Type().Elem()).Elem()
		fill96(k, depth+1)
		fill96(el, depth+1)
		if k.IsValid() {
			m.SetMapIndex(k, el)
		}
		v.Set(m)
	}
}

func cover96Ctx() context.Context {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Millisecond)
	time.AfterFunc(30*time.Millisecond, cancel)
	return ctx
}

func cover96_ptr_FakeKMS(recv *FakeKMS) {
	cover96Call(func() { recv.Wrap(cover96Ctx(), zero96[[]byte](), zero96[map[string]string]()) }) // fake_kms.go:47
}

func cover96_ptr_KMSProvider(recv *KMSProvider) {
	cover96Call(func() { recv.Open(cover96Ctx(), zero96[string](), zero96[Handle](), zero96[string]()) })   // kms_provider.go:94
	cover96Call(func() { recv.Put(cover96Ctx(), zero96[string](), zero96[Secrets](), zero96[[]string]()) }) // kms_provider.go:31
}

func cover96_ptr_LocalProvider(recv *LocalProvider) {
	cover96Call(func() { recv.Open(cover96Ctx(), zero96[string](), zero96[Handle](), zero96[string]()) })   // local.go:83
	cover96Call(func() { recv.Put(cover96Ctx(), zero96[string](), zero96[Secrets](), zero96[[]string]()) }) // local.go:25
}

func cover96_funcs() {
	cover96Call(func() { CanaryWrapUnwrap(cover96Ctx(), zero96[DataKeyWrapper]()) }) // kms.go:23
	cover96Call(func() { NewAWSKMS(cover96Ctx(), zero96[string]()) })                // awskms.go:31
	cover96Call(func() { NewCipher(zero96[string](), zero96[string]()) })            // secrets.go:37
	cover96Call(func() { NewFakeKMS() })                                             // fake_kms.go:30
	cover96Call(func() {
		OpenEnvelopeBound(zero96[*Cipher](), zero96[[]byte](), zero96[string](), zero96[SealBinding]())
	}) // envelope.go:100
	cover96Call(func() {
		OpenEnvelopePayloadBound(zero96[[]byte](), zero96[[]byte](), zero96[[]string](), zero96[SealBinding]())
	}) // envelope.go:266
	cover96Call(func() {
		SealEnvelopeBound(zero96[*Cipher](), zero96[Secrets](), zero96[[]string](), zero96[SealBinding]())
	}) // envelope.go:85
	// skip SealRawEnvelopeWrappedBound (envelope.go:137)
	cover96Call(func() { encryptionContextAAD(zero96[map[string]string]()) }) // fake_kms.go:85
	cover96Call(func() { mapAWSKMSError(zero96[error]()) })                   // awskms.go:92
	// skip openRawEnvelope (envelope.go:214)
	cover96Call(func() { validateCurrentHandle(zero96[string](), zero96[Handle]()) }) // provider.go:116
	// skip wrapWithClock (upstream_wrap.go:57)
}

func TestCoverage96ErrorBranches(t *testing.T) {
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(t.TempDir()); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	var recvptr_FakeKMS *FakeKMS
	recvptr_FakeKMS = new(FakeKMS)
	cover96_ptr_FakeKMS(recvptr_FakeKMS)
	var recvptr_KMSProvider *KMSProvider
	recvptr_KMSProvider = new(KMSProvider)
	cover96_ptr_KMSProvider(recvptr_KMSProvider)
	var recvptr_LocalProvider *LocalProvider
	recvptr_LocalProvider = new(LocalProvider)
	cover96_ptr_LocalProvider(recvptr_LocalProvider)
	cover96_funcs()
}
